/*#include "fillit.h"
unsigned short int  *zeewier(unsigned short int tetrimino, size_t size)
{
    unsigned short int  grid[16];

    return (grid);
}
*/
/*
eerst kijken of A past
zoniet, increment size
dan plaats je A,
probeer A en dan B te passen,
lukt dat niet, probeer C(t/m Z),
lukt niks daarvan, probeer B als eerste en daarna A,

short arr[16];

long* x = (long*)&arr[2];

................
................
##.............. | 16 
##.............. | 16 \ 64 
................ | 16 /
................ | 16
................
................
................
................
................
................
................
................
................
................
*/
